# Generated by Django 4.2.30 on 2026-04-21 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (English)')),
                ('name_zh_hans', models.CharField(blank=True, max_length=100, verbose_name='Name (Chinese)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon (emoji or font-awesome)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('comfort', 'Comfort'), ('suite', 'Suite'), ('luxury', 'Luxury')], max_length=20, verbose_name='Room type')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (English)')),
                ('name_zh_hans', models.CharField(blank=True, max_length=100, verbose_name='Name (Chinese)')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_zh_hans', models.TextField(blank=True, verbose_name='Description (Chinese)')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per night (RUB)')),
                ('capacity', models.PositiveSmallIntegerField(default=2, verbose_name='Capacity (guests)')),
                ('area_sqm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Area (m²)')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='Wi-Fi')),
                ('has_tv', models.BooleanField(default=True, verbose_name='TV')),
                ('has_ac', models.BooleanField(default=True, verbose_name='Air conditioning')),
                ('has_fridge', models.BooleanField(default=False, verbose_name='Minibar')),
                ('has_safe', models.BooleanField(default=False, verbose_name='Safe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['sort_order', 'price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/%Y/%m/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary image')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room image',
                'verbose_name_plural': 'Room images',
                'ordering': ['sort_order'],
            },
        ),
    ]
