# Generated by Django 4.2.30 on 2026-04-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Headline')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Headline (English)')),
                ('title_zh_hans', models.CharField(blank=True, max_length=200, verbose_name='Headline (Chinese)')),
                ('subtitle', models.TextField(verbose_name='Subtitle')),
                ('subtitle_en', models.TextField(blank=True, verbose_name='Subtitle (English)')),
                ('subtitle_zh_hans', models.TextField(blank=True, verbose_name='Subtitle (Chinese)')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Background image')),
                ('badge_text', models.CharField(blank=True, max_length=100, verbose_name='Badge text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Page name')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (English)')),
                ('title_zh_hans', models.CharField(blank=True, max_length=200, verbose_name='Title (Chinese)')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('meta_description_en', models.TextField(blank=True, verbose_name='Meta description (English)')),
                ('meta_description_zh_hans', models.TextField(blank=True, verbose_name='Meta description (Chinese)')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (English)')),
                ('content_zh_hans', models.TextField(blank=True, verbose_name='Content (Chinese)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Доброславия', max_length=100, verbose_name='Site name')),
                ('site_name_en', models.CharField(blank=True, max_length=100, verbose_name='Site name (English)')),
                ('site_name_zh_hans', models.CharField(blank=True, max_length=100, verbose_name='Site name (Chinese)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('copyright', models.TextField(default='© 2025 Доброславия', verbose_name='Copyright text')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='Telegram')),
                ('viber', models.CharField(blank=True, max_length=50, verbose_name='Viber')),
                ('og_image', models.ImageField(blank=True, upload_to='seo/', verbose_name='OG Image (1200x630)')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
