# Generated by Django 4.2.30 on 2026-04-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='address_en',
            field=models.TextField(blank=True, verbose_name='Address (English)'),
        ),
        migrations.AddField(
            model_name='page',
            name='address_zh_hans',
            field=models.TextField(blank=True, verbose_name='Address (Chinese)'),
        ),
        migrations.AddField(
            model_name='page',
            name='email_en',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (English)'),
        ),
        migrations.AddField(
            model_name='page',
            name='email_zh_hans',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (Chinese)'),
        ),
        migrations.AddField(
            model_name='page',
            name='phone_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone (English)'),
        ),
        migrations.AddField(
            model_name='page',
            name='phone_zh_hans',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone (Chinese)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.TextField(blank=True, verbose_name='Address (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_zh_hans',
            field=models.TextField(blank=True, verbose_name='Address (Chinese)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_en',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_zh_hans',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (Chinese)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_zh_hans',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone (Chinese)'),
        ),
    ]
