from django import template
from django.utils import translation

register = template.Library()

# Словарь статических переводов
STATIC_TRANSLATIONS = {
    'ru': {
        'Welcome to Dobroslawa': 'Добро пожаловать в Доброславию',
        'Cozy rooms in the heart of Rostov-on-Don': 'Уютные номера в сердце Ростова-на-Дону',
        'Check-in': 'Заезд',
        'Check-out': 'Выезд', 
        'Guests': 'Гости',
        'guest': 'гость',
        'guests': 'гостей',
        'Check Availability': 'Проверить наличие',
        'Scroll down': 'Прокрутите вниз',
        'Our Rooms': 'Наши номера',
        'Comfortable accommodation for every taste': 'Комфортное размещение на любой вкус',
        'Photo coming soon': 'Фото скоро будет',
        'night': 'ночь',
        'Capacity': 'Вместимость',
        'Area': 'Площадь',
        'Wi-Fi': 'Wi-Fi',
        'Air conditioning': 'Кондиционер',
        'TV': 'Телевизор',
        'View Details': 'Подробнее',
        'Why Choose Us': 'Почему выбирают нас',
        'Everything for your comfortable stay': 'Всё для вашего комфортного проживания',
        'Guest Reviews': 'Отзывы гостей',
        'What our guests say about us': 'Что говорят о нас гости',
        'Ready to book your stay?': 'Готовы забронировать?',
        'Contact us now and get the best price guarantee': 'Свяжитесь с нами и получите гарантию лучшей цены',
        'Book Online': 'Забронировать',
        'Choose the perfect room for your stay': 'Выберите идеальный номер для вашего проживания',
        'No rooms available at the moment.': 'В данный момент номера недоступны.',
        'Capacity': 'Вместимость',
        'Area': 'Площадь',
        'Air conditioning': 'Кондиционер',
        'About': 'О нас',
        'Contacts': 'Контакты',
        'House Rules': 'Порядок проживания',
                'Contact Us': 'Свяжитесь с нами',
        'Contact Dobroslawa Guest House in Rostov-on-Don. Phone, WhatsApp, email, and location.': 'Гостевой дом Доброславия в Ростове-на-Дону. Телефон, WhatsApp, email и расположение.',
        'Get in Touch': 'Свяжитесь с нами',
        'We are here to help you 24/7': 'Мы поможем вам 24/7',
        'Phone': 'Телефон',
        'Available 24/7': 'Доступно 24/7',
        'Chat with us': 'Напишите нам',
        'Usually replies in 5 min': 'Обычно отвечаем за 5 минут',
        'For booking & questions': 'Для бронирования и вопросов',
        'Address': 'Адрес',
        'Central location': 'Центр города',
        'Send us a message': 'Отправьте нам сообщение',
        'Your Name': 'Ваше имя',
        'John Smith': 'Иван Иванов',
        'Subject': 'Тема',
        'Room Booking': 'Бронирование номера',
        'Question': 'Вопрос',
        'Leave a Review': 'Оставить отзыв',
        'Other': 'Другое',
        'Message': 'Сообщение',
        'Contact information': 'Контактная информация',
        'Find us on the map': 'Найдите нас на карте',
        'Open in Maps': 'Открыть на карте',
        'Send Message': 'Отправить сообщение',
        'Email sent successfully!': 'Сообщение успешно отправлено!',
        'Thank you for contacting us. We will get back to you shortly.': 'Спасибо за обращение. Мы свяжемся с вами в ближайшее время.',
'Everything you need to know for a comfortable stay': 'Всё, что нужно знать для комфортного проживания',
    },
    'zh-hans': {
        'Welcome to Dobroslawa': '欢迎来到多布罗斯拉维亚',
        'Cozy rooms in the heart of Rostov-on-Don': '位于顿河畔罗斯托夫市中心的舒适客房',
        'Check-in': '入住',
        'Check-out': '退房',
        'Guests': '客人',
        'guest': '位客人',
        'guests': '位客人',
        'Check Availability': '查询可用性',
        'Scroll down': '向下滚动',
        'Our Rooms': '我们的客房',
        'Comfortable accommodation for every taste': '适合各种口味的舒适住宿',
        'Photo coming soon': '照片即将上线',
        'night': '/晚',
        'Capacity': '容量',
        'Area': '面积',
        'Wi-Fi': '无线网络',
        'Air conditioning': '空调',
        'TV': '电视',
        'View Details': '查看详情',
        'Why Choose Us': '为什么选择我们',
        'Everything for your comfortable stay': '为您提供舒适住宿的一切',
        'Guest Reviews': '客人评价',
        'What our guests say about us': '客人对我们的评价',
        'Ready to book your stay?': '准备好预订您的住宿了吗？',
        'Contact us now and get the best price guarantee': '立即联系我们，获取最优惠价格保证',
        'Book Online': '在线预订',
        'Choose the perfect room for your stay': '选择适合您住宿的理想客房',
        'No rooms available at the moment.': '目前没有可用客房。',
        'Capacity': '容量',
        'Area': '面积',
        'Air conditioning': '空调',
        'About': '关于我们',
        'Contacts': '联系我们',
        'House Rules': '住宿规定',
                'Contact Us': '联系我们',
        'Contact Dobroslawa Guest House in Rostov-on-Don. Phone, WhatsApp, email, and location.': '多布罗斯拉维亚宾馆联系方式。电话、WhatsApp、电子邮件和位置。',
        'Get in Touch': '联系我们',
        'We are here to help you 24/7': '我们全天候为您服务',
        'Phone': '电话',
        'Available 24/7': '全天候可用',
        'Chat with us': '与我们聊天',
        'Usually replies in 5 min': '通常5分钟内回复',
        'For booking & questions': '预订和咨询',
        'Address': '地址',
        'Central location': '市中心位置',
        'Send us a message': '发送消息',
        'Your Name': '您的姓名',
        'John Smith': '张三',
        'Subject': '主题',
        'Room Booking': '客房预订',
        'Question': '问题',
        'Leave a Review': '留下评价',
        'Other': '其他',
        'Message': '留言',
        'Contact information': '联系信息',
        'Find us on the map': '在地图上找到我们',
        'Open in Maps': '在地图上打开',
        'Send Message': '发送消息',
        'Email sent successfully!': '邮件发送成功！',
        'Thank you for contacting us. We will get back to you shortly.': '感谢您联系我们。我们将尽快回复您。',
'Everything you need to know for a comfortable stay': '舒适住宿须知',
    }
}

@register.simple_tag
def static_trans(text):
    """
    Простой тег для статических переводов.
    Использование: {% static_trans "Check-in" %}
    """
    lang = translation.get_language()
    if lang == 'ru':
        return STATIC_TRANSLATIONS['ru'].get(text, text)
    elif lang == 'zh-hans':
        return STATIC_TRANSLATIONS['zh-hans'].get(text, text)
    return text
