# Generated by Django 4.2.30 on 2026-04-21 19:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_stay_nights', models.PositiveSmallIntegerField(default=1, verbose_name='Minimum stay (nights)')),
                ('max_stay_nights', models.PositiveSmallIntegerField(default=30, verbose_name='Maximum stay (nights)')),
                ('advance_booking_days', models.PositiveSmallIntegerField(default=0, verbose_name='Advance booking (days)')),
            ],
            options={
                'verbose_name': 'Booking settings',
                'verbose_name_plural': 'Booking settings',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100, verbose_name='Guest name')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('guest_phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('guests_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of guests')),
                ('check_in', models.DateField(verbose_name='Check-in date')),
                ('check_out', models.DateField(verbose_name='Check-out date')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('special_requests', models.TextField(blank=True, verbose_name='Special requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
